INSERT INTO public.permissions (key, module, description) VALUES
  ('dashboard.view', 'dashboard', 'Ver dashboard principal'),
  ('dashboard.export', 'dashboard', 'Exportar datos del dashboard'),
  ('finance.read', 'finance', 'Ver módulo de finanzas'),
  ('finance.write', 'finance', 'Editar registros financieros'),
  ('finance.approve', 'finance', 'Aprobar transacciones'),
  ('finance.export', 'finance', 'Exportar reportes financieros'),
  ('inventory.read', 'inventory', 'Ver almacenes'),
  ('inventory.write', 'inventory', 'Gestionar inventario'),
  ('inventory.transfer', 'inventory', 'Transferir entre almacenes'),
  ('purchases.read', 'purchases', 'Ver compras'),
  ('purchases.write', 'purchases', 'Crear órdenes de compra'),
  ('purchases.approve', 'purchases', 'Aprobar órdenes de compra'),
  ('hr.read', 'hr', 'Ver RRHH'),
  ('hr.write', 'hr', 'Gestionar empleados'),
  ('hr.payroll', 'hr', 'Gestionar nómina'),
  ('fleet.read', 'fleet', 'Ver flota'),
  ('fleet.write', 'fleet', 'Gestionar vehículos'),
  ('ai.read', 'ai', 'Usar GRIXI AI'),
  ('ai.write', 'ai', 'Configurar AI'),
  ('reports.read', 'reports', 'Ver reportes'),
  ('reports.create', 'reports', 'Crear reportes'),
  ('settings.read', 'settings', 'Ver configuración'),
  ('settings.write', 'settings', 'Editar configuración'),
  ('settings.billing', 'settings', 'Gestionar facturación'),
  ('team.read', 'team', 'Ver equipo'),
  ('team.invite', 'team', 'Invitar miembros'),
  ('team.manage', 'team', 'Gestionar miembros'),
  ('team.roles', 'team', 'Gestionar roles'),
  ('audit.read', 'audit', 'Ver auditoría'),
  ('notifications.read', 'notifications', 'Ver notificaciones'),
  ('notifications.manage', 'notifications', 'Gestionar notificaciones')
ON CONFLICT (key) DO NOTHING;
